export { default as addAggregationFilter } from './add-aggregation-filter';
export { default as addContentType } from './add-content-type';
export { default as removeAggregationFilter } from './remove-aggregation-filter';
export { default as removeContentType } from './remove-content-type';
export { default as removeSearchTerm } from './remove-search-term';
export { default as removeToken } from './remove-token';
export { default as setDisplayType } from './set-display-type';
export { default as setPage } from './set-page';
export { default as setSearchTerm } from './set-search-term';
export { default as setSort } from './set-sort';

import { Fn as addAggregationFilterFn } from './add-aggregation-filter';
import { Fn as addContentTypeFn } from './add-content-type';
import { Fn as removeAggregationFilterFn } from './remove-aggregation-filter';
import { Fn as removeContentTypeFn } from './remove-content-type';
import { Fn as removeSearchTermFn } from './remove-search-term';
import { Fn as removeTokenFn } from './remove-token';
import { Fn as setDisplayTypeFn } from './set-display-type';
import { Fn as setPageFn } from './set-page';
import { Fn as setSearchTermFn } from './set-search-term';
import { Fn as setSortFn } from './set-sort';
export type CatalogDriverActions = {
  addAggregationFilter: addAggregationFilterFn;
  addContentType: addContentTypeFn;
  removeAggregationFilter: removeAggregationFilterFn;
  removeContentType: removeContentTypeFn;
  removeSearchTerm: removeSearchTermFn;
  removeToken: removeTokenFn;
  setDisplayType: setDisplayTypeFn;
  setPage: setPageFn;
  setSearchTerm: setSearchTermFn;
  setSort: setSortFn;
};
