const path = require('path');
const {
  gatherQuerySources,
  buildFragmentMap,
  transformDoc,
  hashQuery
} = require('./../lib/helpers/graphql');
const util = require('util');
const { parse, visit } = require('graphql/language');
const { print } = require('graphql/language/printer');
const { ContentFragment } = require('./test-query-files/ContentFragment');
/**
 * Note, `expectedHash` is taken from hashes generated by Apollo Client
 * when making requests utilizing queries idential to the ones from the test files.
 *
 * https://github.com/thoughtindustries/helium/blob/c1d6910f3d85f515e1a5345675145c9736fc3e27/tooling/template-base/lib/init-page-context.js#L40
 */

describe('@thoughtindustries/tooling/cli/helpers/graphql', () => {
  describe('buildFragmentMap', () => {
    it('builds a map of fragments contained in an array of query sources', async () => {
      const querySources = await getQuerySources([
        './test-query-files/QueryWithFragment.js',
        './test-query-files/ContentFragment.js'
      ]);

      const fragmentMap = buildFragmentMap(querySources);

      expect(print(fragmentMap['ContentFragment']).trim()).toEqual(print(ContentFragment).trim());
    });
  });

  describe('transformDoc', () => {
    it('adds typenames to queries when they are not included', async () => {
      const querySources = await getQuerySources(['./test-query-files/QueryNoTypename.js']);
      const fragmentMap = buildFragmentMap(querySources);
      const modifiedDoc = transformDoc(querySources[0], fragmentMap);
      const { hash } = hashQuery(modifiedDoc);

      const expectedHash = 'eb8d6793d8388429017820a420f65ac5e6e26cdb69be437dd5ff5639cdeb31a3';
      expect(hash).toEqual(expectedHash);
    });

    it('adds FragmentDefintion to Document definitions when FragmentSpread is included in SelectionSet', async () => {
      const querySources = await getQuerySources([
        './test-query-files/QueryWithFragment.js',
        './test-query-files/ContentFragment.js'
      ]);

      const fragmentMap = buildFragmentMap(querySources);
      const modifiedDoc = transformDoc(querySources[0], fragmentMap);
      const { hash } = hashQuery(modifiedDoc);

      const expectedHash = 'c89fd25eccebf029bacf8b3b2097138edb3729ee4b59620dfb3de8584e911cbd';
      expect(hash).toEqual(expectedHash);
    });
  });
});

async function getQuerySources(filePaths) {
  const resolvedFilePaths = [...filePaths.map(filePath => path.resolve(__dirname, filePath))];
  return gatherQuerySources(resolvedFilePaths);
}
